
apiVersion: v1
kind: Service
metadata:
  name: app-lb-service
  namespace: nourakalotaibi-tawazun
  labels:
    app: tawazun-app
spec:
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
    name: app-service
  type: LoadBalancer
  selector:
    app: tawazun