apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  namespace: nourakalotaibi-tawazun
  labels:
    app: Mysqldb-svc
    name: NouraKAlotaibi
spec:
  type: ClusterIP
  ports:
    - name: mysql-svc-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: Mysqldb