apiVersion: v1
kind: PersistentVolume
metadata:
  name: tawazun-app-pv
  namespace: nourakalotaibi-tawazun
  labels:
    type: local
    app: Mysqldb
    name: NouraKAlotaibi
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"

