apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-deployment
  namespace: nourakalotaibi-tawazun
  labels:
    app: tawazun
    name: NouraKAlotaibi
spec:
  template:
    metadata:
      name: tawazun-pod
      labels:
        app: tawazun
    spec:
      containers:
        - name: tawazun-container
          image: noura93/tawazun1:latest
          resources: 
            requests: 
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "600m"
          ports:
            - containerPort: 8080
          startupProbe:
              initialDelaySeconds: 3
              periodSeconds: 2
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 2
              exec:
                command:
                - touch
                - hello.txt
          env:
            - name: DB_URL
              value: mysqldb
            - name: DB_NAME
              value: mysql
            - name: DB_USERNAME
              value: mysql
            - name: DB_PASSWORD
              value: mysql
            - name: DB_PORT
              value: '3306'

  replicas: 1
  selector:
    matchLabels:
      app: tawazun