apiVersion: v1
kind: Service
metadata:
  name: Mysqldb-service
  namespace: nourakalotaibi-tawazun
  labels:
    app: Mysqldb
    name: NouraK Alotaibi
spec:
  type: ClusterIP
  ports:
    - name: Mysql-svc-port
      port: 3306
      targetPort: 3306
  selector:
    app: Mysqldb