apiVersion: v1
kind: Service
metadata:
  name: tawazun-app-service
  namespace: nourakalotaibi-tawazun
  labels:
    app: tawazun-svc
    name: NouraK Alotaibi
spec:
  type: NodePort
  ports:
    - name: tawazun-svc-port
      port: 8080
      targetPort: 8080
      nodePort: 31000
      protocol: TCP
  selector:
    app: tawazun