apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: nourakalotaibi-tawazun
  labels:
    app: Mysqldb
    name: NouraKAlotaibi
spec:
  template:
    metadata:
      name: Mysqldb
      labels:
        app: Mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          resources: 
            requests: 
              memory: "600Mi"
              cpu: "600m"
            limits:
              memory: "800Mi"
              cpu: "800m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "mysql"
            - name: MYSQL_PASSWORD
              value: "mysql"
            - name: MYSQL-ROOT-PASSWORD
              value: "mysql"        
          volumeMounts:
            - mountPath: /dbvolume/data
              name: tawazun-app-volume
      volumes:  
        - name: tawazun-app-volume
          persistentVolumeClaim:
            claimName: tawazun-app-pvc

  replicas: 1
  selector:
    matchLabels:
      app: Mysqldb

      