kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: nourakalotaibi-tawazun
  name: aws-pvc
  labels:
    name: NouraKAlotaibi
    type: aws-pvc
spec:
  accessModes:
    - ReadWriteOnce
resources:
  requests:
    storage: 3Gi
  selector:
    matchLabels:
      type: aws-pv
