apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: nourakalotaibi-tawazun
  name: aws-pv
  labels:
    name: NouraKAlotaibi
    type: aws-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-07676b003556f2ae1
    fsType: xfs
