apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: nourakalotaibi-tawazun
  labels:
    app: Mysqldb
    name: NouraKAlotaibi
spec:
  template:
    metadata:
      name: Mysqldb
      labels:
        app: Mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "mysql"
            - name: MYSQL_PASSWORD
              value: "mysql"
            - name: MYSQL-ROOT-PASSWORD
              value: "mysql"  
          livenessProbe: 
            tcpSocket:
              port: 3306
            initialDelaySeconds: 2  
            periodSeconds: 2 
            timeoutSeconds: 1 
            successThreshold: 1 
            failureThreshold: 3         
          volumeMounts:
            - mountPath: /dbvolume/data
              name: tawazun-app-volume
      volumes:  
        - name: tawazun-app-volume
          persistentVolumeClaim:
            claimName: tawazun-app-pvc

  replicas: 1
  selector:
    matchLabels:
      app: Mysqldb

      